# Lang
language: zh-CN

# Dark Mode
dark: false

# Header
menu:
  首页: /
  归档: /archives

# Your Feed Location
#rss: /atom.xml

# Content
fancybox: true


# Miscellaneous
google_analytics:
favicon: /favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:


# Profile
nickname: 小紫baby
description: Web开发者，价值投资实践者

# Load fontawesome icons? Also see the links option
icons: false

# Footer area links
# NOTICE) If you set "icons: false" link names will be clear text
# If "icons: true" link names will interpreted as fontawesome icon names
# NOTICE) Use the fontawesome icon names without the fa- prefix (http://fontawesome.io/cheatsheet/)
links:
  博文: /archives/
  开发: https://github.com/simongfxu
  投资: https://xueqiu.com/u/1333966811


# Info
archive_footer_content: 只有逆向思维才能让你与众不同。
post_footer_content: 你做着和他人一样的事，却想脱颖而出，这不可能！

# Gitment
gitment:
  owner:
  repo:
  client:
    id:
    secret:


# Donate
donate:
  github:
  paypal:
  bitcoin:
  BTCQR:
  AliPayQR:
  WeChatQR:
